---
title: "Scientific Practice Notes"
output: pdf_document
---

# Imports 

import ../../Modules/Biology/Viruses as Viruses

import ../../Modules/Biology/BiologicalMolecules as BiologicalMolecules

import ../../Modules/Biology/Solutions as Solutions

import ../../Modules/Biology/ScientificReasoning as ScientificReasoning

import ../../Modules/Biology/AcidsandBases as AcidsandBases

import ../../Modules/Biology/Steriochemistry as Steriochemistry

import ../../Modules/Biology/Electrophoresis as Electrophoresis

import ../../Modules/Biology/Immunology as Immunology

import ../../Modules/Biology/Microorganisms as Microorganisms

# Scientific practice

## Course Details

## Background

### __Solutions: Solutions__

### __BiologicalMolecules: Biological Molecules__

### __ScientificReasoning : Scientific Reasoning__

### __AcidsandBases : Acids and Bases__

## Lab Techniques

### __Electrophoresis: Electrophoresis__

## __Steriochemistry: Steriochemistry__

## __Immunology: Immunology__

## __Microorganisms: Microorganisms__


# New Notes

## ATP 
Channel for frotein passage is lost due to arginine with postitive charge. as the pH is very low the proteins attach to an asparatage causing a confromational changeinthe helix of the asparateate to bury it leading the C subunit to rotate, as this happensthe proton will eventually get to the other side. The alp0ha and beta subunits are connected to the C subunit and change with it, leading to the conformational change required for ATP synthesis. 

aspartate on the C subunit and arginine in the channel on the A subunit, are stabalise each other by electrostatic interactions, which allows the asparate to remain in the hydrophobic membrane despitre its charge. However once the aspartate is protonated to asparagine this interaction is greatly weakened and so the C subunit it with its polar group is forced into the interior of the protein (due to a hydrophobic, hydrophilic interaction. This change promotes conformational change of other proteins. 

ATP synthase can operate in reverse when there is a very high concentration of ATP. To show experimentally that it rotates a filament of fluorescent actin was attached to the protein. 

QUESTION: do changes occur through electrostatic or mechanical interaction. (probably occurs through the environment)

How are electrons of cytosolic NADH fed into ETC, (in the matrix). These electrons are incoperated to re-oxidise NADH, ($NAD^+$ regeneration very important in citric acid cycle). 

This interaction occurs via shuttle systems. 


There are two shuttle systems which deliver electrons from cytosolic NADH without physicality transporting NADH without physically transporting NADH across the membrane. 

### Glycerol phosphate shuttle 
irreversible, functioning at both high and low concentrations of NADH. 

Consists of two glycerophosphate dehydrogenases, one of which exists within the cytosol, it functions of dihydroxyacetone phosphate reducing it to glycerol-3-phosphate, and in the process oxidises the NADH produced in reaction six. (the electrons are transferred to the glycerol 3 phosphate organic substrate) 
The second glycerol phosphate dehydrogenase functions within the inner membrane of the mitochondrion. Takes in the glycerol 3 phosphate and re-oxidises it via a Flavoproteins within the membrane. (this is Flavoproteins 4, ), (will also go to ubiquinone in the membrane joining into the ETC)



### Malate aspartate shuttle, 
transports both ways depending on relative concentration. 

There is oxaloactetate within the Cytosol that is reduced to malate. NADH from reaction 6 is reduced regenerating $NAD^+$. Malate can be transferred across the membrane, and once inside the Malate can be oxidised as part of the citric acid as normal. The electrons from the Malate are then transferred to NADH which goes to complex one of the ETC. when cytosolic NADH is very high oxaloacetate is covered to aspartate to cross membrane, and oxaloacetate reduction occurs to form Malate. Only happens when [NADH cytosolic] > concentration in matrix. Oxaloacetate is transported out as aspartate. 

## ATP per glucose
glycolysysis
phgase 1
2 used 

phase 2 
4 produced

net
2 produced

pyruvate dehydrogenase
2 produced.

TCA cycle
2 produced glucose.
6 NADH
2 $FADH_2$

estimated 


The amount of ATP generated is dependant on the shuttle. as they enter the ETC at different time so diffs amount of proteins pumped out of the membrane. 

1.6ATP per cytosolicNADH via glycerophsphateshuttle 
2.7 ATP per cytosolic NADH via]s malate-aspartate shuttle
2.7 per NADH formed in pyruvate decarboxylase
1.6 ATP per TCA cycle $FADH_2$ 2.7 ATP per TCA cycle NADH


## Gluconeogenesis and glycogen metabolism
glucose comes from the breakdown of starch or the breakdown of glycogen. 

### Gluconeogenesis

> NOTE: The reverse of glucose metabolism, functionally however it does not involve exactly reversed metabolic pathway. 
	gluconeogenesis is the synthesis of glucose, 
	glycolysis is catabolism of glucoses. 
	ATP used in gluconeogenesis, produced in glycolysis. 
>NOTE Oxidative processes are oxidative in nature. 

Different key regulating enzymes to glycolysis to ensure spontenaity. 

& of the ten steps of glucolysis are reversedin glyconeogenesis. 

Reaction2, and 4-9 are the same. There are 4 niques reactions in gluconeogenesisreplaceing the three regulatred reactions in glycolysis, that is reaction 1 3 and 10. 

### NEw reactions 

#### 1
Pyruvate carboxylase. catalyses the conversion of pyruvate to oxaloacetate. 
PEP, carboxykinase, catalyses ther conversion of oxaloacetate to PEP

Fructose 1-6 bisphosphatase 
$F1,6 BP \rightarrow F 6P$ glucose-6-phosphatase $G-6P \rightarrow$ glucose. 

COPY IMAGES from text book. Gluconoegeneisis inintraited by conversion of pyruvate to PEP in 2 uniques energy requiring enzyme catalused reactions. (both reactions require energy)

As two ATP molecule are required per glucose 4 ATP are required and 2 GTP per glucose. 
2 pyruvate molecules are needed to create 2 GAP which will combine with DHAP to form F1,6BP. 

## Pyruvate carboxylase reaction
$pyruvate + bicarbonate+ ATP\rightarrow Oxaloacetate+ ADP + P_i$ Enzyme is dependant on biotin (coenzyme) (COPY structure). Acetyl Co-A is an allosteric activator. The gamma phosphate of ATP is donated to the bicarbonate to form carbonylphosphate, the carbonyl phosphate reacts rapidly with the biotin to form n carboxyl biotin and release inorganic phosphate. (carboxylation of biotin requires the presence of acetyl-CoA). The enzyme extracts a proton from the N-carboxyl biotin to from a carbanion, and overall oxaloacetate is formed. 

> NOTE: Acetyl CoA is an activator of pyruvate carboxylase, which makes sense as high High CoA implies that glycolysis and citric acid cycle are both operating a lot, implying that a lot of glucose is being metabolised, and there is a high demand for glucose so more glucose should be made available. 


>NOTE: Pyruvate carboxylase involved  is an anapleutrotic regulation reaction.  



#### Energetics
Gloconeogensis is still a spontaneous process (as the step are not completely reversed)


about 160 g are used per day, about 20 grams are carried in the blood at any given time. Glycogen stores provide less that 200 g of free glucose (only about a days supply of glucose available in the body)

Small non-carbohydrate precursors can be anabolically synthesised into glucose. Contracting molecules generate pyruvate which can be converted back into glucose via the process pf gluconeogenesis. 

90\% of glucose is generated in liver most of the rest in kidneys, glucose is mainly metabolised in brain and muscles. 
Anaplerotic reaction increases th flux of TCA cycle. 

## Fungi Metabolism
fungi are typically secondary or tertiary consumers. Require, 

Carbon nitrogen phospherous sulphur potassium calcium magnesium other trace elements. 

### BIosymthesis pathways
Krebs cycle, glycolysis, pentose phosphate.

### Glucose is the preffered carbon
free glucose is limited,somust digest more complex glucan polymers. 
aquire sugars through active and pasive uptake, constituitive(always active) or induced (only turned on under certain conditions)

Rapid resonce S cefvivisiae over 100sugar transporters as competitionso important,global transcriptional rergulator CreA (binds to glucose or other environmental stimulator,leads to phosphorylation cascade which leads to activate of uptake pathways).

Uptake, glucose is preferred, the is a hierarchy of uptake, the sugars which require less energy are taken up first.

Fructose is the preferred monosaccharide.

### Nitrogen

#### Preferred sources
cannot use elemental nitrogen. 
nitrate,ammonia. Key role of fungi in nitrogen cycle. 

ammonium is released by decomposes from deamination of amino acids in proteins. 

#### Ammonification 
conversion of organic nitrogen to ammonia. 

#### enzymes

##### GS: glutramine synthetrase

ATP depepndant productionof glutaminefromammoniaandglutamate. 
12 identical subunitsof 50 kDa.
saccharomyces cerevisiae actrs are 

#### GOGAT: glutamine2-oxoglutaratee aminotransferease. 
Iron sulphur falvoprotein N-terminal nucleophile amdin transferase. 
reductive transferer of the amide group. 

#### Phospherous. 
conitinuously required from growth. 

##### Cellular uses
phospholipid bilayer, replicating DNA. RNA, ATP. 

Fungi are very important in natural rock weathering, especially lichens and mycorrhizae
use physical pressure. Turgor pressure, to essentially break rock apart. 
Or chemical proton based or ligand based degradation. 

###### ligand base
organic anions siderophores, lichen acids, and other polyphenolic acids, and acid polysaccharides. 


##### Low molecular weigh organic anions are the most important group 
Oxalate, and citrate, strong acids, bi and to do and trivalent metal cations. 

$AL{^3+}, Fe^{3+}, Ca^{2+}, Mg^{2}$ lowers the activity /concentration of free cations,leading to a concentration gradient between the rock and the environmental promoting calcium to move out of the rock. Leads to slow degradation of the rock.  	

Copy. 

COPY PATHWAY IMAGES. 

### secomdary metabolsim andseconary metabolites. 
not absorlutely required for survival, pathways are branched and interlinked, only porduced during the stationarty phase, micotoxins, and antibiotics, provide a compeditive edge for the fungi. 

Growth curve module.

cell numbers are doubling. 

#### Three broad chemicals 

##### Polyketides
complex biological chemicals which are highly biologically active. non ribosomal peptides. independant of mRNA.often cyclinc or branched inculde antibiotics or pigments. 

##### non-ribomsomal peptides. 

Terpenes 
organic compounds that often have a strong odour.


generes are often clustered together expression can be coordinately regulated generally. 

Secondary metabolism/ metabolites. 

Psilocybin, phsychedelic compounds (hallucinogenic). produced by more than 200 muschroom species psilocybin mushrooms 
genus psilocybe. 1st isolated in 1957 trytamine hallucinogen simlar to LSD. psilocybin is converted to psilocin after ingesion. Psilocin binds to serotonon receptors, in the CNS serotonin antagonist. Feel good hromone. 5-HT2A causes reduction in brain flow to certain types of the brain, stimulates cross talk between different parts of the brain, reactivating old pathways and developing new pathways. causes cross talk between different parts of the brain. closely connected with learning and memory. 

poteontial treatment formajor depression and addictive orders. 

psilocybin is metabolsimed mostly in the liver,(very little secreted by the kidneys), converted to 4-hydroxyindole-3-acetaldehyde 

forms glucurnoide toxin elimination strategy 

$<5\%$ of the oral psilocybin is extreted vai the kdineys. 

cant find in blood after 24 hours/ or seven days controversty. 

four major genes. four major genes psiD psiM psiH psiK. Of the five species sequenced 4 have a single promoter 1 has two, single regulator,van bing to different promoters. 

psilycibin regulated, so requires licenses to work on it. original model on syntheisis, has chagned. psiD carboxylated L-tryptophan, to from trytamine, methalataed by psiM to from Dimethyltryptamine, oxidition by psiH to Psilocin phosphorylatedf by psiK, dephosphorylated in liver. 

Newer synthesis path. 

psiK actually has two steps. 2 molecules of ATP are used in its metabolism. 

environmental applicatio
mechanism of action suggests metaxoans are the principal targets animal is multicellular. 


## Interactions

### mutulaism 
both organismsbenefit

### Commensalism 
one benefits

### COmpetition /combat
both detrimented

### paracitism 
one detrimentaed by other

### Ammensalism
one negatively affected other unaffected 

### neutralism 
neither area affected. 

### Mycorhizzae
microhizziae is the association. extended network, over 700 times water and nutrients. mutualistic assiciation with plants so they bothe benefit. fungi get photosynthate from the plant platn gets nutrinets adn minerals scavenged by the fungi. 

#### Arbusdcular/ endomicorhizzae
penentrates individual cell walls forming arbuscules. the majority are glomeromycetes. ectomicorrhizae form a sheath around the outside of the root.

#### Ectomicorhizze
the majority are basidiomycota. 


plant and bacterial interactions
cannot fix own nitrogen so recruit nitrogen fixing bacteria, which fix nitrogen converting it to ammonia. the most common is rizobium. motile, non-sporulating,rods, nodules. bacteria get carbon sugar. 

Root nodule formation
rhizobium bacteria, bacteriodesencopoerated,grow and expand to from the root nodules. bacteriodes loose their membrane (dont need to generate ATP anymore.) some tropical legume species rely on AMF to form nodules, in te absence of AMF they will not form an association with rhizobia. In these nodules there is a direct link between phosphorous absorbtion and nitrogen fixation. (becuase nitrogen fixation is so expensive). 

truffles are fruit of ectomicorhizae, innoculating orchards takes yeast and has no garuntee. 

truffles associated with hazel and oak trees,ascomycete,produce ascospores truffle itself is ascus, 100g of black tasmanian truffle= R2630. aroma comes from sulphulr containing volatiles. specifically thiopenen derivatives, (this is what pigs and dogs find). some truffles dont actually have genes for thiopene synthesis, it actually does not make it own cell. fungi have there own microbiome. differ between individuals but there are core species shared such as rizobium

so GC-MS was used 
Gas chromatoraphy mass spectrometry, used for phoresic works, explosive detection etc. identify different substrates all the way down the the molecular level. different retension time, also quantifyable. two peaks from running whole fruiting body, mycellium with fruiting body after steralisation (get rid of bacteria, nothing, then just steralised fruitingbody still no thiopenes, bacteria with fruiting body extract,thiopene 1 and two extract with bacteria but killed bacteria still no thiopenes. repeat experiment kills bacteria so levels went down, but fuingicide didn't . bacteria gets ATP carbon adn phospherousn from the reationship. fungi gets nitrogen + spore dispersal. 

mycoviruses
first identified in 1960 in agaricus bisporus, malformed fruiting bodies.mostly shperical with dsRNA genomes. spread via dirrect contanct between hyphae and in anastomosis. 


most fungal viruses are asymptomatic, some increase fungal virulence somedecrease it someincrease temperature tollerance, usually to higher temeprature. (grass fungi virus higher temperatures).

### Animal assocaitions
Panda rely on gut microbiome to degrade nutrients, the fungi recieve food, or get trasnported to fopd, termitesbeatles wasps ants and larger herbivors. i

### paracytes

Caudicepts, zombie fungus, ascomycete, preffered host is formacean ants. 

spores stick to host exoskeleton, then germinate and penetrate host by enzymatic degrdationand turgor pressure, then switches to yeasts morphology which spread through the ants throughheamocyte.then secretes a nerve toxin to alter ant behaviour, so ants leave colony bight underside of leaf, of branch. treduce mictocondira around mandibles so that while ant dies mandibles do tno release. hyphae erupt from the joints to help anchor the insect to the leaf. 3-4 weeks for friuting body to develop. produces a number of polyketide metabolites, when the ant has attatched to the leaf polyketes are produced (digest ant muscle to stopit from moving.). produces antibacteria, to surpess ants native baceteria which would compete. also makes nathoquinones.
quinones are antomalteria metabolites. uncleawr why these are released, by just be horizontal gene tranfer. 

Chytridiomycosis
infectious disease in amphibians decline extintion of 200 frog species, batrachochytrium dedrobatidis BD, chytrid, flzgellatedspores called zoospores believed to be as a result of environmental stress pollution etc. opportunistic pathogens take advanatgaea f annopportunity not normally availabel such as a host with a weakened immune system an altered mcriobiata,

shiped over for lab experiments,probably how fungus got to america. 
