
# Course Background. 

The course is a high level background, very little detail. 

## Background. 
Not full notes are provided, no notifications for new content uploads to sakai, A lot of work outside the scope of the lectures is not included/focussed on. 
Everything in the prac manual is included. 

# Microorganisms. 
Bacteria and viruses are considered to be microorganisms, the 'cut off' is that a microscope is required. 

Such microorganisms can be mulualists, some are pathogens. The are also vital in mantaining the geochemistry planet cycle.

Microorganims are both producers and decomposers, (they produce organic sugars both by photoynthesis and by chemolithotrophic. 

## Appilications. 
The two major applications of microorganisms are in production of fermented foods and beverages (for example beer/ethanol in any alcohol and yogurt) and industrial chemicals for example insulin. 


### Human impact. 
Microorganisms can lead to food spoilage. When humans eat food contaminted with microorganisms they are t risk of severse sickness of even death, either because the microorganism themselves are toxic or because some product of their metabolism, eg a waste product is. Closely related is the risk of infection from ingesting a pathogenic micro-organism. 





## Hi
