## Field Trip 
(Dont be late, leave be there 12:15 12:30, back by 6:00)
Bring shoes good for walking, not affraid to get wet. (Delta waders provided as peeps got skin rashes, )

## Introduction to sach sheet 
Stnadardisation + quality control. (Sash 5 protocol. RSAS) + other papers in resources on SAKAi.  we will use simplified document. 

### ADvantages 

 #. little equipment. 
 Macroinvertebrates easilyIDed . 
 Techniques simply, 
  Good + quick indication of health (look for pollution sources in field)
  gives the total/ integrated picture. 
 
INsects respond to and integrate many different impacts, so loss of sensitave insects does not imply a specific source/type of pollution. Cannot ID the source, does nto specify when a pollution event occured. Limmited by high flow rates (in flood dangerous), low flow rates (SASS poor for ephemepheral, as animals dissapear becuase of lack of flow not pollution, so used only for perrenial rivers. It is however a red flag indicator.

### Site selection 
Rocky/riffle difs from pool, choose a site reprisentative of reach of river sampled. Try not to have pollution sources, ie storm water drain, sewerage, etc. 
There mmust be available habitats at the site which are available to sample. 

### Safety 
Can you swim (decent life jacket)
Dangerous wildlife, crocs + hippo's. 
Waders, 1 keeps legs dry and avoid dirrect contant with polluted water. Sass newt, used to navigate, check depth, and stabalise crossing. knife to cut away trapped boot. Sun hat or cap, polerized sunglasses, 

NOTE: not using SASS net, so much less robust do not use as walking stick. 

## Equipment 

### Net 
standard SASS five square opening 30 x 30. 100mm pore sizeallows small organisms to wash through. 

Sample onto tray, three biotropes, animals kept in three separate bottles for each of the  three separate biotropes (not ID in field)
SASS five identification sheet, 
Aquatic invertibrates iof SA field guides, + book on families. magnifying glass, for caddis flies hydrocyclids etc. small sucker + forcept. sucker with net on the end, ice cube tray, for beetids and hydrocyclids, with three columns. 
pen pencil and clipboard. 

clear water to wash (esp turbid river)

### Biotopes 
Sampled site must have the full variabliity of habitats, 
  #. Stones
  #. vegitation 
  #. GSM, (gravel sand and mud)
## Choosing sites 
 
### Stones 
Brick size rocks, pick up turn over look at organisms, check stones in current and stones out of current. Vigourously turn stones, hold net far away only sample for a total of 2 minutes. IF stones are largley bedrock hard to turn over thaen extend up to 5 minutes but then this must be recorded. 

Must range left and right as well as upstream and downstream. Stones out of current, at most a minute sampling (range across the site)

NOTE: not critical to find stones out of current, but stones in current are essentail. 
hand picking + visual observaatinos. stuff which the net doesnt pick up such as waterpennies or freshwater sponges which are ot easily disslodged.

Bugs on surface, try to make a note, such as waterstriders (jarred bugs. 
Stones in current and out current are analysed together. 

Common errors, (not sufficeintly virourously turned over rocks , not enough organisms dislodged. 
TEndancy to go over two minutes. 
Water sampling must be connected to main channel not isolated back water. )

### Vegitation 
vegitation on the size of the river/ marginal vegitation, or within the river such as reeds seges and grasses. 
 2 meters in total, 0.5 meters in each type of vegitation. (sqaure of linear. ))
 IN or out of current. (for us reprisentation is more important than quantity. so get vegitation in both slow and fast water. must dislodge stuff clinging to wegitation to brush wegitation wityh SASS net. 
 veg in current and veg out of current is combined. Can oversample or oversample 2 meter length, go across diffs types of vegitation, (look around for aquatic vegitation. 
 Gravel sand and mud
 ))

## 

