---
title: "Aquatic Ecology" 
author: "Keelan Krinsky"
output: html_document
---

# Imports

import Modules/EvaporativePotential as ep

import Modules/AquaticEcosystemTaxonomy as AquaticEcosystemTaxonomy

import Modules/SARiverDistribution as SARiverDistribution

import Modules/WaterQuality as WaterQuality

import Modules/Rivers as Rivers

import Modules/Wetlands as Wetlands

import SavannaHydrology as SavannaHydrology

import MatterCycles as MatterCycles


# Aquatic Ecology

## Background

### __ep: Evaporative Potential__

### __AquaticEcosystemTaxonomy: Aquatic Ecosystem Taxonomy__ 

### __SARiverDistribution: South African River Distribution__

### __MatterCycles: Matter Cycles__

## __WaterQuality: Water Quality__

 
## __Rivers: Rivers__


## __Wetlands: Wetlands__

## __SavannaHydrology: Savanna Hydrology__





## Inputs

## Background 

### Definitions 

#### Primary production 
The synthesis of biomass of capture of energy from light and nutrients. Biomass becomes 

#### Secondary production 
For heterotrophes, secondary production, is the conversion of consumed biomass to living biomass. 

#### Energy budget 
equation that balances gain of energy (production ) with loss respiration and excretion of waste products. 

#### Transfer effeciency 

##### Consumption effeciency 
how much of the food source is actually consumed 

##### Assimilation effeciency 
how much of the food eaten is actually assimilated, i.e does not pass through the body without being metabolised.  

##### Production energy 
how much of the absorbed biomass actually is converted into living biomass. 
Biomass production = consumption - excretion - respiration. 

#### Net primary prodution 
the amount of biomass available for consumption by heterotrophes. 

#### Gross primary production 
The amount of biomass perminantly fissed by plants. 
Energy is lost by respiration at every trophic level. 


#### Primary producers. 
Secondary consumers, 

## Food web 
shredders feed on CP, and browsers feed on 

Planktonic communities are dominated by primary production, whereas in rivers the majority of the base material is dead organic material, hence grazers dominate waters and lakes, and Collectors dominate headwater streams. 

### Nutrient spiralling 
detritus 
consumers,
decomposers 
water column. 

there may be nodes, such as reeds, or carneleads (fly larvae), which trap nutrients, untiltil some disturbance pccurs. hence they flow of energy slows down and speeds up as it moves through the water column, adjacent wetlands can also act as nodes in the system. 

### Energy budgets/ nutrient budgets. 
Planktonic (lake) communities are primarily autochthronous, ie locally produced within the ecosystem. 

benthic stream communities end to be primarily allochthonous, (ie nutrinets are produced primarily outside the system and comming in. 

The source of much of the energy in the a stream comes from the terrestrial plant material. Macro-Invertibrate emmergance, terrestrial invertibrates rely on aquatic ecosystems for energy. terrestrial organisms are feeding on the subsidy coming from the terrestrial ecosystem. 

For example in the western united states of america, samon which swim up river get trapped in dams, to mantain the population hatcheries are raised and them dumed into the river when they get old enough, Mergansers a duck like bird prey on the samon smolts. 

When the smolts are dropped in Miganzers migrate to the stream, and then dispurse as the fish run out. , Mergansers exploit the free lunch. 
Food webs. 

### Rivers are four dimentional ecosystems. 
(find paper),  Ward JV 1989, The four-dimensional nature of lotic ecosystems. L.N Am. Benthol, Soc.,.

### Longitudinal dimension 
Rivers dictated by abiotic conditions (shift from headwaters to lowland flood plains. 

COPY IMAGE. 

Biological gradient. 

Additional trophic levels, potentially different feeding groups, Different nutrient flows, Nutrients can be transported upstream or downstream by anadromous (sea to river) or catadomous (river to seas) fish. Socae samon run. Samon become so adapted their mouth parts change to fight off other males to get to females but they are so adapted that they cannot eat food so they starve. HEnce they die forming piles of dead fish in the trees, which serves a a food source for grizzle bears, (which they require as a food source to build up fat reservwes for hibernation, bald eagles also rely heavily on the sammon runs. )

Eals in SA, live in stream but go out to sea to sporn and die. 

There are fundamental changes in the respiration going on between head water streams and lower down in the river, with consitent respiration, and production patern in the longitudinal organisation of the stream. 

In the riparian reaches there is alot of rithronic cover, which leads to shading so little energy in the form of light avaiable to aquatic plants and algae for photosynthesis, howvere there is lots of dead plant material from these terrestrial plants available of r herbivours, so the ration of energy by respiration : energy by primary production is greater than 1. 

Lower down these is more lgiht avialable, and more nutrients, in the form of dissolved particles, whcih leads to increased NEP from plants algae and diatoms, leading to more energy fixed by live organisms in phtosynthesis than the energy being processed by decomposers in the stream. 

On into the potamonic area of the river, where there is a higher susepnded load, some of the available light is blocked by the sediment, and the sandy substrate is not as good for benthic diatoms, or macrophytes, also as there is more accumulated biomater in the stream, there is increase in dead organic material,, so there is a switch back to increased energy proceeed by respiration comparted to photosynthesis. (in this case it is more the collectors than the grazers that are doing the bulk or the energy processing as they have more food available). 

The ratios of feeding groups changes moving longitudinally along the stream. at the head waters there are arge quantities of collectors , eating corse of finer organic material{?}. 

In the middle reachers there are more grazers, feeding on diatoms etc, 

in the lower reaches there are again collectors dominant, (especially those adapted to feeding on fine organic materia such as blood worms, )
in big rivers, bivalves are also present, feeding as filter feeders in the muddly waters. (require lage muddly systems, as where SA rivers go into limpopo. 

NOTE: all of this falls under the RCC river continum concept. 

### Problems. 
The concept is very broud so caution is required in its use. 

Firstly , functional feeding groups dp not allways translate across biogeographic zones. For, example stone fly preditors are found in upper and lower river, but others in a differnt family are grazers so are not found all the way along the river, this is a problem in SA where there is a huge variety of unknowned macroinvertibrates, there is limited capacity for insect taxonomy For example one common family is the betidee whch are extremely variety in their feeding morphology/biology, so the family level is not sufficeint for RCC. Many africa river systems such as the savanna system do not follow proposed model. 
assignment to feeding groups difficult

IN american there are tress out of pine forests, etc.

Most of the native trees do not form a canopy in SA, in amgalesburg the canopy cover is 80\% invasive.
poplar and seringa particularly are invasives which shead lots of leaves to the rive, in a pure savanna however.  

## LAteral dimension 
There is both active and passive movement of organisms from the riparian zone to the river, (including reparian wetlands. 

Moviment from the river into the riperian zone. ). The moviment of macroinvertibrates (insects) in and out of the river in thier life cycle (larvae vs adults) constitutes active moviment/ nutrient cycling, there is also passive transfers. 

Flooding drives biotic composition of the riparian zone river channel morphology. temperature distribution of allochthonous material. (temperauter is affected as ground water moves up, (presumable regulates temperature more stricktly. )). 

## Vertical 
Many organisms move actively between the benthos and the hyporheos, to utilise resources, and avoid disturbance. 
many organisms move actively between benthos and hyporheos to utilise resources , avoid disturbance. 

Communities within unconfined alluvial aquifers are poorly understood, as the aquifer can potentiall range far from the river chaneel (2km) and can be several meters down. 

Well drilled (2km from the stream), larvae startced hatching out.  Ground water can serve as a source of dissolved organic nutrinets particularly N and P compounds that support primary production at upwelling zones in the river, active transport such as animals burrowing down and comming out also occurs between the two systems. 

## Temporal 

Can occur at various different time scales. 

### Lotic ecosystems experience environmetnal change over period of day (diurnal , yearly (seasonal), decades centuaries etc. 

#### Diurnal 
temperature, light intensity, oxygen concentration in the water. 

#### Seasonal 
Drives fish spawning 


which sacle to use,depends on the organism and the process under study, for example phtosynthesis is diurnal and well as seasonally dependant. seasonal vs catastrophic flooding in Mpumalanga is a;sp an important example where scale must be considered. 

FOr example one in a hundered year flood wiped out entire riparian zone, which can massively resetthe ecosystem. In general the scale of the impapct is generall related to the time between impact events. 
within a year a microhabitat will change. 
habitats such as the arrangment of trees in the riparian zone will be over several years eg with flooding patterns. 
an entire secrtore could change every few decades. and an entrie flood plain would change more in the order of thousands of years, an entire drainage basin drains on the order of hunders of thousands of years. 


Rivers are highly interactive with surrounding ecosystems, both laterally and vertically. SEveral theories exist to explains aspects of these re;ationships, but each must be considered in context, (ie european is similar to invasive dominated SA system with forest in headwaters, but in classical SA open headwater RCC not very well followed. )

A spatio-tempral perspective of rivers allows us to understand how humans distrupt these processes. 
(Critical to understand what we 'should see') to work on managment processes. 
# Special adatations of aquatic animals in freshwater 

## Regulation 

### Osmo-regulation. 
Freshwater environments are less saline than the bodies of aquatic organisms 

#### Freshwater. 

##### Skin exchange. 

In fresh water an osmoregulating fish takes up water through its skin, and actively takes up ions through its gills, It drinks little water , and excretes dilutes urine 

COPY IMAGE. 

#### Salt water 
In salt water an osmoregulating fish loses water though its skin, drinks ample water, excretes ions through gills, and excretes concentrated urine. 

##### Skin exchange 
looses water passively through skin due to osmotic pressure. 

##### Urrination 
excretes concentrated urine. 
NOTE: Salmon can osmoregulate in both environments. 

#### Physiological mechanisms 
Reabsorbance of salts. 
Active ion uptake. 

#### Energy consequences 
There may be an energetic cost of osmoregulation which drives smaller size in freshwater streams. (for example crayfish, although there are other explanations, such as greater food availability, there is more detritus available in marine environments. ).

#### Thermoregulation 
water tends to be thermally stable (especially in systems with a well developed thermocline. This means that most aquatic organisms can afford to be poikilothermic. (there body temperature is allowed to adjust passively to that of the outside environment. ). Such animals tend to be uni-therms, ie they are adapted to a wide range of different temperatures. 
This is achieved through temperature compensation, there are both metabolic and behavioral techniques for maintaining body temperature. 


#### Respiration
Maximize surface area of respiratory tissue, and maximize the rate of flow of oxygenated water , (while minimizing the surface area though which they can loose / gain unwanted water  or salts which disrupts their osmotic balance.). This leads to a conflict between respiration and osmoregulation, where an optimum must be reached. Most animals are adapted to deal with this problem with gills, which differ in shape and surface area depending on the particular environment of the given organism (species). for animals in less oxygenated water  The gill is either a big leaf shape or consists of multiple strands, 
For Baetidae and Heptageniidae which live in fast flowing oxygenated water the gill is more streamlined, and a bit smaller. Plecopteran , ventilate their gills by flapping their legs to increase current. 

In dragon fly larvae a rectal gill is used, which allows for propulsion by sucking in and pushing out water. 
Some insects have normal insect spiracles, such insects developed adaptions such as a "breathing tank" in beetles with a substrate cavity, above the trachea. Bugs tend to use a with plastron hairs which trap air bubbles. some others such as mosquito larvae use what is essentially a snorkel 

### Mantenance of position in lotic waters. 
the current can often be extremely strong, this can be dealt with by 

##### aviodane behaviour 
moving during floods, and in general living in sheltered areas such as behind boulders, 
Body shape which is streamlined helps as well as attachment morphological features for gripping onto the substrate. 

##### Body shape 
the heptageniid mayflies are extremely adapted so that they can live and feed on the surface of the rock surface, this body shape means the current pushes the insect down onto the rock, the tail is used as a rudder to steer the mayfly. 
Claws (mayflies suckers (Blepharacerideae simuliidae, or a silk cord which they attatch and can climb back up if they happen to fall off the rock.  silk nets, (hydropsychids, muscular foot, gastropods. )))

#### Lentic waters. 
As there is not flow for passive movement, active movement is required, however animals such as plankton still require at least vertical movement for example to stay on the right side of the thermocline. 

Fish maintain there buoyancy with a swim bladder, an organic attached near the top of the spine, 
Algae have trapped gas/oil bubbles, water hyacinth have lacunae (large air filled structures within the stem. 

### Migration 
There is a lot of migration occurring in the vertical direction, it is still an active process, exhibited by most pelagic plankton species, generally they are in deep water in the day moving up to shallower water at night (migrating at dusk). 

Predators avoidance during the day, such as from fish, and other visual hunting predators, 
energy conservation , stay warm enough that metabolism is working without using energy to cool down, move up at night to feed on phytoplankton. 

NOTE: still don't want to be below thermocline as their is low oxygen 
(in summary, find food, don't becomes food, and regulate metabolism). 

There are predators within the phytoplankton which tend to follow their prey, such as (?) which follow copepods.

#### rivers. 

##### Drift. 
downstream transport by the current of benthic animals. It is a voluntary behavioral adaptation. 

###### CAtastrophic 
animals which are involved in catastrophic, unpredictable disturbance. 

###### Behavioural drift. 
individual organisms or small groups or organisms which all move into the water column due to a particular stimulus, ie to avoid predation or to find food. Active decision made based on a common driver in the background habitat. 
Escaping from a local stress, abandonment of a substrate. drift is a very energy efficient way of moving around (compared to using muscle contractions to move along the stone. avoid attach from a predator. Generally higher at night. trout make drift dangerous as they sit by an area of low flow next to an area of high flow and eat stuff coming down the high flow area, trout are visual predators so more dangerous in the day. 

NOTE: catastrophic drift is orders of magnitude higher than the normal level of drift seen. 

For example in the rotenone drift animals let go on mass even beatles which using their own air to breath were not yet affected, but could still smell the posion. 

###### Advantages of drift. 
Works in ballance with tendancy in adults to fly upstream. which in combination drives dispersal. which helps to mediate competition for food and space. Drift can allow for rapid recolonization after a disturbance event such as a flood. provided there is an upstream refuge area. (post flood drift. ). 

### Re[roduction and dispersal 
both sexual and asexual reproduction is seen in freshwater systems. 
In certain situations asexual reproduction is very useful as it is very rapid, has low energy cost and can easily be used to take advantage of friendly areas such as temporary ponds. (which have lots of food an d no predators. ). the disadvantages are low or no genetic variation which leads to vulnerability to population crashes and extinctions. most can do both, organisms switching to sexual production when the environment starts to change.for example males produced as stream dries up so that genetic variation in eggs produced just before the whole pond dries.  

###### Cosnant 
animals which let go by accident or which just generally drift. 


## Type of fertilisation 
Overall sexual reproduction is much more widely found than asexual reproduction 

### Broadcast spawning 
the gametes are put directly into the water column, and form zygotes, basically for sessile animals. 

for mobile animals there is more active fertilization, often in a spawning bed, in the case of salmon female makes a Redd,  a space to lay eggs, male fertilizes eggs as they are released, this is external but localized. 

In insects there can be internal fertilization. 

In freshwater organisms ranges from broadcast spawning through to internal fertilization. A large portion of marine invertebrates are sessile so rely on the water column for mixing and dispersal, this is possible in the sea because there are a lot of strong currents allowing for mixing of gametes and dispersion of offspring to new areas. 

not so much broadcast spawning in rivers and lakes. 
In lakes because there is very little current. wind reach can lead to mixing but still far less than that induced by wave action and ocean currents. In rivers gametes only move downstream so things don't necessarily mix properly, (ie is males produce before females all sperm are gone downstream before eggs arrive. this spawning mechanism is optimized for rocky shores. 

## Spawning aggregations. 
strongly linked to season, temperature and flow. (selecting parts of the habitat which are ideal for incubating eggs))
female finds good bolder releases pheromone all males in the water come behind he, lays eggs in small bunches which stick to rocks, males all pile in to try and lay release their sperm. some males come right up to touch the females, ignore other things in their environment. scavengers will try and eat loose eggs which come past in the water column. In a big spawning aggregation individual chances of being picked off by a predators are lower. 

Competition for successful copulation / fertilization 
mating territories (e.g. odonates) defend /competed for by males, females entering this territory will be courted. the male who mates with the female last is most likely to pass on his genetic information. engage in mate guarding, male hangs onto female to prevent her from mating with other females. mating aggregations in insects also occur, which are characterized by synchronized appearance and swarming. many groups emerge on mass most classically mayflies. Some mayflies live only 24 hours as adults, so emerge mate and die. mating aggregations tend to focus around land marks for example caddis flies around a particular tree. mating swarms maximizes the opportunity for all different organisms to find a mate. generally all males, deceases interspecies competition, ensures constant between sexes. territories vs aggregation is to an extent species vs individual. leads to high increased predator attraction but still overall risk of individual predation risk is decreased. 

Dispersal of eggs tends to be done upstream of of eggs spawning sites. In the case of freshwater systems eggs are generally laid on rocks, sometimes vegetation, in lentic systems there are not many rocks so eggs are normally laid on marcophytes at the edge of the stream, or on rafts which float on the surface of the water. 

Overall reproductive strategy 
r vs k selection 

## R selection 
many small, insects. In general r selection is most common in fish insects and crustaceans for freshwater systems, generally more eggs/young produced by planktonic forms than macro-invertebrates, which tend to lay small batches, several batches in different places but still overall less eggs. 

## K selection 
fewer larger eggs. cylincoid fishes from lake Malawi, mouth brooders <100 about 20, eggs at a time.  

### Population dynamics of the system. 
Organisms compete among each other and with other specie for limited resources. When there are plentiful resources there is rapid increase in population size. A mismatch between resources and consumers will result in population losses through one of two routes. mortality and dispersal. the number of fish in a given region of stream may fluctuate, and increasing because of increased resources, and then dropping because of dying of movement to avoid competition. 
COPY IMAGE. 

the overall birthrate in the population will decline as resources decline, one birthrate and mortality are equal a balancing point is reached which is the carrying capacity of a particular habitat. Intraspecific competition for stable limited resources means populations will be kept below a stable threshold maximum. 
depending on the rate of resource distribution change die offs and increases may be more for less dramatic, emerging adult black flies disperse at higher rate id the local population density of larvae is too high. COPY IMAGE>  such dispersal patterns are found in fish as well as in macroinvertibrates, fish however because of their size have a lot more requirements in terms of ideal environments for spawning, (COPY IMAGE). For example in particular season water temperature, fall to the right range and all fish moved up to particular places along the river, larvae drift down stream to go into shallow backwaters, safe from predators, but with lots of food. 

overwintering, rivers free over, so fish must find thermal refuges in the winter, in SA fish will find optimum habitats for feeding and for predation risk, daily or seasonal migration between refuge and feeding habitat occurs in a single reach. In ephemeral, or temporal rivers, source sink dynamics are seen, for a serious of pools in an intermittent stream, fish move between refuge pools and pools which dry up in dry season, so constant reshuffling, reproduction and overwintering in resource habitats. refuge habitats would change from year to year. so fish reorganize depending on the season and water . temporary habitats are sinks as they do not have the possibility to sustain a fish for a long time, so there is a movement between source and sink habitats. expand from permanently wetted refuges into temporarily wetted sink habitats. fish populations in temporary systems are a good indication of expand (resources in the source pools will fluctuate with varying population levels). 

### Adapting to life without water    
many lentic and lotic environments are naturally episodic or intermittent nonetheless aquatic organisms still thrive in these systems, and adapt by evolving resistance to desiccation and/or resilience to habitat loss. 

there are many temporarily which can form cysts, such as fairy shrimp, the eggs are resistance to desiccation not the adults. flexible reproductive strategy, resistant cysts or eggs, resistant immature /adult stages (low metabolic state, moist membrane ). escape by flight (insects which flying adults)/ burrowing (hand out in the ground water, such as certain species of talapia. ). rapid re-colonization (resilience ) 

Wet phases can also be harsh, such as catastrophic flood, use hypoheos, during floods. burrowing can be used to survive both drying out and flooding. burrowing into the hyperheos. Lungs fish is extremely drought resistant. As the water level falls lungfish burrow into the bottom nu to form a cocoon and aestivate through the dry season. eastivating as an adult is an extreme drought resistance adaptation. Killifish tend to live in temporary ponds, lay drought resistance eggs or cysts in sediment of drying ponds, which hatch when water returns Killifish (_Northobranchius_) lay aestivating eggs. 

## animal ecology in fresh water systems.
competition and adaptation, aquatic organisms vary in their abilities to self regulate and survive environmental variability.  This variable adaptation among species have different strategies to cope with environment predators, and competitors. because of theses varying adaptations and strategies there are specific environmental conditions in which a species is able to sustain a population which is known as a niche. 


### Fundamental niche. 
the full potential set of environmental conditions a species could survive in, given no competition. however all organisms have to compete with other similar organism so the loser o the competition get shrunk into a smaller subset ie the realized niche, 
 
### Realised Niche.
the actual sub-set of these environmental conditions in which the species is observed to survive, given real levels of competition with other species. 

shifts between fundamental niches happen on evolutionary time scales. for example two groups of sticklebacks in the Columbia glacial lakes. during the last ice age there were expansions and contractions which moved lakes and rivers, driving potential speciation, hence there were multiple invasions of lakes by sticklebacks (which are river fish). subsequent invaders had to compete with the sticklebacks already there, overtime theses groups shifted their fundamental niches away from each other overtime evolved a limnetic form , and a benthic form shifts in fundamnetal physiological biology, such as number of gill rakers in the body (note when there are two species the range of physiological characteristics of each are confined to a smaller  )range, longer gill rakers in limnetic fish feeding on plankton. the most extreme example of speciation and niche differentiation is the Malawi fish. (cillonlids.)
 
### Community as a whole  
disturbance in structuring freshwater communities, community structure can be described as being controlled by two interacting forces. 

competition and disturbance, if competition dominates community structure., such as lakes like Malawi of British Columbia, the community i deterministic as the process of niche differentiation is very predictable 

whereas if the community is disturbance driven a stochastic, ie randomly organised community results, intermediate levels of river bed disturbance supports highest benthic diversity. Animals which are highly resistant or resilient tend to dominate in very high disturbance species, In communities with both disturbance and competition there are the most species with resistance and resilient colonizers and competitive species. Intermediate levels of river bed disturbance support highest benthic diversity (COPY IMAGE) Intermediate disturbance hypothesis. 

the relationship between disturbance and productivity can also be compared, (COPY IMAGE). When there is very little food available/ low productivity there will always be low diversity even with high disturbance, as productivity increases the effect of disturbance is far more pronounced with intermediary disturbance levels leading to high diversity.
if disturbance is low animals like snails which are protected and good at feeding dominate, at high disturbance snails are not very mobile so mobile generalist resilient species tend to dominate, both will co-occur at intermediary levels. 

### Predation as distrubance. 
Blugill sunfish in American streams. rapid spawning allows rapid expansion of blue gill populations the intensity of the blue gill as a mortality source to its prey leads to variation in their impact, (on macroinvertibrates). By feeding on abundant prey such species act to mediate diversity by controlling competitively dominant species. disturbance can have a knock on effect on predators and their ability to mediate prey. for example trout are very efficient predators, so will wipe out local fish (galaxiids) if they reach a certain minimum population size, however trout are far less resilient to flooding, . the bed stability can be used as a indication of which species will be present in very stable beds, (low flood disturbance, ) trout only, conversely in low bed stability, high flooding only galzxiids, and in intermediary levels there is co-oncurrence. In general co-co-occurrence is more frequent in disturbed streams. 

predatory exclusion limited to stable streams. 


## Freshwater fish invasions. 
test OLS 1029

### Source of fish 

#### History 
recfeational fishign only really became a thing in the late colonal period, there was a push by the goverment in terms of legislation to bring in popur anglican speciess, uch  crtp, rinbow trout, borwn trout, 1876 egition encourge importing nging pecie, init tocing or rectretion purpoe, pre through tte progrm, COPY IMAGE. 

South ric w a sourceor pred through the ret o outhern ric. 

COPY imge, 
extrimit pecie re thoe that have been moved round, there were very few sspecie in the natural ystem even a few introuced species are a big problem, Sharptooth catffish ffrom great fissh to itte issh into the uny, 
 
countries with very large natuarall fish diversity are not very affected, stock for aanging, biocontro ,  

trner

video, red tail fish. water quality improved. 

Clan William sandfish , illiminate blue gill. rotanone project to irradic
