---
title: "Concepts Notes"
output: html_notebook

---
 
# Imports
import Modules/Genetics as 

import Modules/Metabolism as Metabolism

# Concepts Notes

## Background

### __OrganismTaxonomy : Organism Taxonomy__

## __Genetics: Genetics__

## __Metabolism: Metabolism__

## New Notes

### gluconeogenesis
happens in the cytosol. 

### PEP carboxykinase in matrix and cytosol. Oxaloacetate can leave the matrix as malate (or asparate). oxaloacetate is converted to malate, to be moveed across the membrane, malate is then oxidised back to oxaloacetate and gluconeogensis can commentce. Pyruvate is converted onto the mitochondrion at the end of the cirtr4ic acid cycle. pyruvate carboxylase used to convert it to oxaloacetate or PDC used to convert it to acetyl co A, which is made into citrate (which can go to fatty acid synthesis or TCA cycle). Oxaloacetate can go to the citric acid cycle or it can be the starting poitn for gluconeogenesis. 

phosphoenol pyruvate is a high energy compound as the enol is an unstable form. To make phosphoenol pyruvate from oxaloacetate PEP carboxykinase is used and GTP is required. carbon dioxide is removed. in the first reaction a carbon is added in the second reaction it is removed. this is necessary as they decarboxylation which is very favourable energetically helps to from the very high energy phosphoenol pyruvate. decarboxylation is a favourable process that helps to form the very high energy PEP, hence the first reaction is essentially a priming reaction.

2rd from last 
fructose 1,6 bisphosphatase.  fructose 1,6-bisphosphate to fructose 6 phosphate. hydrolysis of phosphoester bond therefore thermodynamically favourable. allosteric regulation. citrate fructose 2,6 bisphosphate. if there is alot of citrate there is no need to brak down glucose to make more citrate, instead in can be built up. 

last reaction 
glucose-6 phosphitase reaction 
final step, glucose is the product from G-6P this reaction does not occur in the cytosol, it happens within the endoplasmic reticulum. hydrolysis occurs to creaate glucose and phosphate. the glucose and the phosphate are released into the cytosol separately. glucose has to then get into the blood so it can be transproted to the brain of mucles, the GLUT 2 tasnporter is used. 

net reaction: 

$2 pyruvate+4ATP+2GTP +2NADH+2H^++6H_2O\rightarrow glucose+4ADP+2GDP+6Pi+2NAD^+$ $\Delta G =-37.7kj.mol$

>NOTE: GTP hydrolysis is slightly less energy than ATP hydrolysis. 

gluconeogenesisi is exergonic whilethe reverse of glycolysis is not this is bacuse 5\4 additional high energy phosphate bonds are hydrolysed which provides the 


## glycogen and startch metabolism

### Structure

#### Glycogen 
$\alpha$ 1-4 linkages with $\alpha$ 1-6 linkages, there is only one reducing end per glycogen (same with startch)

>NOTE: alpha yj OH is in the cis configuration. 

$\alpha$ Amalyase is an endoglycosidase. 
hydrolyses $\alpha 1-4$ glycosidic linkages at random positions, maltose, maltotriosem and small oligosaccharides. limit dextrins are left over as the $\alpha$ 1-6 bonds cannot be easily cleaved. glycogeon phosphoralyase in animals is an exoglycosidase cleaving off the last glucose. the phoshporysis reactive unti to alpah D -glucose 1 phoasphate, which can enter glycolysis dirrectly. limit dexteracne are still produced. 

Branching alows for more rapid breakdown, as the exoglycosidases can only act of free ends. 

additionaly enzymes are required to debranch the limit detxterans. 

### Debarnching enzyme
cuts off a section from the branch and adds it to the long chain, however it still cannot cleave the 1-6 bond, cleaves one to four of the link just behind it. alpha 1-6 unit activity of the enzyme is then used to cleave off the isolated branch glucose. the main section cut off is added to the reducingt rsedction of the main chain.


an unbranched bolysaccheride with one fewer glucose is the end product. 

## Fatty Acid catabolism: $\beta$-oxidation 

better than sugars for storage as very good at packing. 

### fatty acids, cpmefrpmdiet make up 60\% of the callories divided into fatty acids, and triacyl glycerols. major stored energy reserve of fatty acids. stored as large aggregated modules is agrigocytes. 

how they are broken down and how they provide energy. complete combustion of fat os 37Kj/g where as sugars are onyl 17.

tryacyl glycerols go into stomach, a small portion of these will be broken up into lipases. Then reaces the doudenum where alkaline pancreatic lipases htfrolyse TAGs at C1 and C3, esterases hydrolyse ester linkages. FAs+ glycerol made into new TAGs and lipoproteins. 

aceyl co A synthetiase catalyses the addition of acetyl-coA to the end of the fatty acid. The CoA comes from TCA cycle. 

step 2
	oxidation at the beta carbon. cleavage between the alph and beta carbon releases acetyl co A and the cycle can begin again each cycle u\yield four electrons 2 in FADH_2 and 2 in NADH, in the addition of coASH ATP is hydrolysed to form AMP and PP pyrophospahte. second step is hydrolysis of pyrophosphate releasing more energy. this second hydrolysis is required to close the eqillibrium, so 2 ATP equivalents are used up. oxidation via FAD reduction removal of $H_2$. a double bond is formed electrons were released protons were removed. 

	hydration reaction, water added across doulbe bond, then another oxidation reaction, sending electrons to NAD to from NADH the FADH_2goesby flavoprotein 3 into the ETC. after the second oxidation a carboyl group forms on the beta carbon which primers the $\alpha$ beta bond for cleavage. two carbons area chopped off from the long chain. re adds coA (which does not require ATP as release of the two carbon compound provides enough energy, so only the first time coA is added is energy required.n /2 acetl n/2-1 coenzymes:)
