---
title: "Concepts Notes"
output: pdf_document
---

## Review 
MHC I most of body MHC II on cells of the immune system. NM  (polypeptide variation) vs ABO blood groupings

## Receptor response pathways 
The portion which extends into the extracellular environment, possesses thee site which interacts with the ligand. In general, the ligands are compounds such as hormones neurotransmitters and growth factors. On binding of the ligand the receptor undergoes a conformational change. The conformational change in response to ligand binding activate a site on the cytoplasmic end of the receptor molecule. The activated site can broadly speaking do one of two things. One, it can directly catalyse a reaction with a target substrate. Two, It can initiate a reaction which serves as the first step in a series of reactions, that ultimately lead to the cellular response. This series of reactions is what is referred to as the signal transduction cascade. There are three general distinguishing characteristics of receptor-response mechanisms. Firstly, the ligand that acts as the extracellular signal, does not enter the cell to produce the response. Purely binding to the extracellular component is sufficient to trigger the response. Secondly, if the ligand is inserted directly into the cytoplasm, no response is elicited. Thirdly, the receptor itself remains in the plasma membrane while the cellular response is initiated. The receptor molecule does not enter the cytoplasm in order to initiate a response. Cells have many different types of receptors which are stimulated by a large variety of signals. However, the internal response mechanisms, follow relatively (relative to the number of ligands and receptors. ) few pathways which have several features in common. One feature which is shared, and possible central to the production and control of signals is the activity of a group of enzymes known as the protein kinases. 

Protein kinases are enzymes that attach phosphate groups derived from ATP to target proteins. Addition of the phosphate group to the target protein can stimulate, or inhibit the activity of the target protein (It was though only activation was possible). Target proteins in signal transduction, include the receptors themselves, enzymes carrying out critical steps in metabolic pathways, transport proteins (e,g ion channels ), ribosomal proteins, and finally proteins regulating gene activity (transcription factors). The type of cellular response produced depends on the types of protein kinases present in that cell. The presence of the kinases is controlled ultimately by the regulation of genes within the cell. In these receptor response pathways the phosphate groups which are added by the protein kinases can be removed, by another group of enzymes collectively known as protein phosphatase's, which counteract the action of the kinases by continually removing phosphate groups from target proteins. There are two major modes, that are responsible for transducing signals from mammalian cells. In relatively few systems the protein kinases activity is in built into the receptor itself, in the cytoplasmic component of the receptor. More commonly the protein kinases are separate molecules, that operate in the subsequent steps of the reaction sequence, initiated by the receptor. 

### Receptors with integral protein kinase activity
Although ablatively few have integral protein kinase activity the cellular responses controlled by these receptors are amongst the most fundamental in a mammalian cell. For example, the receptor which recognises and binds the hormone insulin, which controls glucose uptake, and thereby the rate of many metabolic reactions in target cells. Other receptors for example the EGF (epidermal growth factor), and the PDfG (platelet derived growth factor) also fall into this group and are central to the growth and division of in mammalian cells. Binding of the ligand generates the conformational change, generally theses receptors have a signal transmembrane range domain which is commonly $\alpha$ - helical, or can phosphorylate the receptor itself. Therefore these proteins are commonly known as RTK's, receptor tyrosine kinases. Phosphorlyation of the receptor itself is referred to as autophosphorylation. In this mode the proteins which are targeted for phosphorlyation are usually enzymes which control key steps in the metabolic pathways, or proteins which control gene activity (transcription factors). In this mode the addition of phosphate groups to targets may activate or inhibit the target proteins activity.


### Receptors with separate protein kinase activity (Mode two)
Receptors in this category are much more varied and numerous than receptors which integral kinase activity. Can i kill him, please kill me first. The receptors in this group are complex proteins, with several transmembrane components, commonly seven, Binding of the signal (i.e the ligand), is also referred to as the first messenger, and activates an enzymatic site on the cytoplasmic side of the receptor. the cytoplasmic site catalyses the first step in a series of separate reactions, which activate one or more protein kinases. The primary reaction series, triggered by the activated receptor, follows one of two distinct but similar pathways. In both of these pathways, the first step catalysed bu the receptor is the activation of a G protein. Because theses proteins bind the nucleotides GTP and GDP. Each of the two pathways, has its own set of G proteins. 

### G proteins. (Guanosine Triphosphate-binding proteins)/ GTPases 
Mammalian cells use G proteins to regulate a range of functions. For example, transduction of signals, but also, regulation of the cytoskeleton, membrane traffic, nuclear transport, and protein synthesis. All of the G proteins share a homologous core domain, that binds a guanine nucleotide, in addition they have a common enzymatic cycle of GTP binding, hydrolysis and product dissociation, to switch, the target protein on or off. Not all GTP binding proteins are related. Tubulin for example is a GTP binding protein, and some bacterial proteins bind and hydrolyse GTP but through completely different mechanisms to the G proteins involved in signal transduction. The conformation of the G protein depends on whether FTP of GDP is bound. The GTP bound form is active, i.e it can interact with and stimulate target proteins/ effector proteins. The GDP conformation is inactive and cannot bind effectors. GTP hydrolysis, and product dissociation, switches the G proteins from the active to the inactive state. The presence of absence of the $\gamma$ phosphate of GTP is the molecular switch between on and off. Most GTPases bond guanine nucleotides with high affinity, but hydrolyse GTP relatively slowly. The G proteins accumulate in the inactive GDP state, until receptors catalyse the dissociation of the GDP, which makes it possible for them to bind GTP, there by activating the G protein. They will remain active until they hydrolyse GTP. The binding of the effector proteins or other regulatory proteins, clearly would precipitate the inactivation step. There are several families of G proteins, created through gene duplication and divergence, but only four main categories have been categorised. 

#### Small GTPases
signals regulating various cellular functions, contains about 6 families, signal amino acid domain of about 200 residues. For example, RAS falls into this family. These GTPases transfer signals from the surface signals  influencing a number of cellular processes, including cell grow, cell polarity, the actin cytoskeleton, vesicular trafficking, nuclear transport and the assemble of the mitotic spindle. Specific regulator and effector proteins interact with each of the six families. 



#### Trimetric GTPases 
signals from multiple helix receptirs. 

#### Elongation factors
ensuring fidenly of protein synthesis. 

> NOTE: Only the protein kinases involved in signal transduction are being referred to. 
