---
title: "Tutorial two"
output: html_document

---

# Imports

import Modules/BeerLambert as BeerLambert

# Tutorial Two

## Question #1

There are two distinct $\lamdba_{\text{max}}$ values:\newline 

 #. $\lambda_\text{max}=260nm$
 #. $\lambda_\text{max}=350nm$

By Beer-Lambert Law\footnote{See appendix} 

 #. $1.2=3.62\cdot 10^{-3}mol\cdot dm^{-3}\cdot 5.00cm$\newline 


## Appendix

># Beer-Lambert Law
>The Beer Lambert law related the attenuation of electromagnetic waves to the properties of the material through which they are propagating and the distance which they have propagated through the material. 
>
>## Equation.
>For a particular wavelength incident on a suspension of absorbing particles the Beer Lambert law is given by:\newline 
>
>$A=\epsilon bC$
>
>Where: \newline 
>> $A$ = Absorbance \newline 
>> $\epsilon$ = Molar absorptivity ($L\cdot mol^{1-}\cdot cm^{-1}$)\newline 
>> $C$= Concentration of absorbing particles. 
>
>## Appendix
>
> ># Absorbance
>>Absorbance is a measure of the extent to which a substance transmits electromagnetic radiation. 
>>
> >## Equation
>>Absorbance (A) is defined by equation to as: \newline 
>>
>>$A=-\text{log}_{10}$. ($=\text{log}_{10}(\frac{I_0}{I})$)\newline 
>>
>>Where:\newline 
>>> $T$ =Transmittance. 
>>> $I_0$ = Intensity of incident radiation and 
>>> $I$ = Intensity of transmitted radiation. 
>>
> >## Appendix
>>
> > ># Transmittance
>>>Transmittance is a material property relating to how radiant energy moves through a substance. 
>>>
> > >## Equation
>>>The transmittance (T) of a surface is given by the expression. 
>>>
>>>$T=\frac{I}{I_0}$ 
>>>
>>>where: 
>>>>$I_0$ = The intensity of light incident onto the surface
>>>> $I$ = The intensity of light transmitted by the surface.
>>>
>>>> NOTE: Transmittance is often given as a percentage.
>>>
>





# Appendix

