---
title: "CHEM2003 Notes"
output: html_document 
---

# Imports

import Modules/Spectroscopy as Spectroscopy
import Modules/OrganicChem as OrganicChem 
import Modules/InorganicChem as InorganicChem

# __InorganicChem: Inorganic Chemistry

># Spectroscopy
>
>## Background
>Spectroscopy is a set of techniques in which the response of molecules to the input of energy is measured. Electromagnetic radiation is applied to compounds and the interaction of this radiation with the compound is then observed. 
>
> >### Electromagnetic waves
>>
> >#### Wave nature.
>>Electromagnetic waves consist of and electric and magnetic field which oscillate orthogonally to each other, and orthogonally to the direction of propagation of the wave. 
>>
> >#### Wavelength
>>Wavelength is donated by $\lambda$ and measured in meters (sometimes nm are used such as when UV or visible light is being discussed). 
>> 
> >#### Velocity
>>Speed is donated by $c$. The speed of light in a vacuum ($c_0$) is constant ($3.00 \cdot 10^{8}m\cdot s^{-1}$), normally the speed of light is given in $m\cdot s^{-1}$ 
>>
> >#### Frequency
>>Frequency is donated by $\nu$ (?) and is measured in Hertz (Hz) that is $s^{-1}$
>>
> >#### Wavenumber
>>Wavenumber is donated by $\overline{\nu}$, and is the reciprocal of wavelength. It is measured in $cm^{-1}$ and used most commonly in IR spectra. 
>>
>
> >## Infra Red Spectrometry
>>Interact with bond stretch, affecting vibrational energy levels. 
>>
>>
>
> >### Gamma Rays
>>The energy of photons is too high breaking up molecules changing their structure. 
>>
>
> >### X Ray Spectroscopy
>>The energy of photons is too high breaking up molecules changing e
>>
>
> >### Ultra Violet and Visible Light Spectroscopy
>>Affect the valence electrons of molecules exciting them to a higher state. 
>
> >### Microwave Spectroscopy
>>Affect bond bending. 
>
> >## NMR Spectroscopy
>>Affects the energy levels associated with the magnetic field which is associated with electron, or protons within the nucleus.
>
> >## Double Bond Equivalents
>>The advantage of double bond equivalents is that they can be used to at least propose several possible structure for a compound. The presence of several structural components including double or triple bonds, cyclic compounds and aromatic rings can be speculated, and the related functional 
>>groups identified. 
>>
> >### Aromatics.
>>The DBE for a benzene ring is 4, and in general if a compound has a DBE above 4 there is a good chance that it contains benzene, (if its DBE is below four then obviously it cannot contain benzene.)
>

># Organic Chemistry
>
>## Course Background.
>
>### Lecturer
>Dr Kennedy Ngwira, C407, Dr Amond Rouseou. C503. 
>
>### Isomers.
>
>#### Structural isomers.
>Structural isomers are compounds with the same atomic composition and molecular formula, but different atomic arrangments.
>
>#### Structural isomers
>#### Stereo isomers.
>
>##### Conformational
>Conformational isomers are characterised by free rotation around a particular (C-C) bond, hence at least one single bond is required in the structure. Due to the free rotation the different isomeric forms can be rapidly interconverted. 
>
>###### Staggered
>In eclipsed conformation, when view along the axis of the bond the groups attached to the atoms of the bond do not lie dirrectly behind eachother but are displaced by a given angle ($60^\circ$) 
>
>###### Eclipsed.
>In eclipsed conformation, when view along the axis of the bond the groups attached to the atoms of the bond lie dirrectly behind eachother. 
>
>###### Cyclic compounds
>cyclic compounds can also form coformational isomers which take on the boat, or chair conformation. 
>
>
>##### Geometric
>Geometric isomers require a rigidn unit such as a double bond ($\pi$ bond), or a cyclic compound which prevents free rotation.
>
>###### Cis trans.
>In cis trans nomeclature the cis conformation has groups of higher proprity on the same size, the trans has them on opposite sides. ( higher priority is assigned to the group which is connected by the atom with the higher atomic number, if atomic number is equal then mass number is used))
>
>###### Carn-Ingold Prelog (E,Z)
>The Carn-Ingold Prelog system (C.I.P rules) are used to assign priorities.  higher priority is assigned to the group which is connected by the atom with the higher atomic number, if atomic number is equal then mass number is used. If the first atom is identical then the atomic weight of the next atom in the chain is compared. multiple bonds are considered as an equvalent number of single bonds to the given atom. 
>
>If the higher priorety groups are on the same side then the molecule is in Z conformation (where Z stands for Zussamen/together). If the higher priorety groups are on opposite sides then the molecule is th the E, Enitgen conformation. 
>
>##### Enantiomers (Optical isomers)
>
>Moeluces whise mirror images are not superimposed. 
>
>###### Requirements.
>$sp^3$ hybridised carbon, with four differernt substituents ()i.e a steric carbon. 
>
>The sp^3 hybridised carbon must have four different groups attatched to it.(For example alanine). The resulting system is asymetrical, and will have a non-superimposable missor image. 
>
>
>NOTE: the central carbon may be refferd to as a steriocarbon, a steriogentic centre or a hydrocarbon. 
>
>###### Properties.
>Inantomers have practically identical(almost indistinguishable) physical and chemical properties are therfore very hard to separate. Furthermore Racemic mixture are hard to detect. This is porblematic as often one inatomer may be a powerful medical drug and the other may be seriously toxic. 
>
>###### Polarised light
>inantomers will rotate plane polerised light differently. They will rotate the plane of polerised light to the same extend to one will rotate to the right (+, dextrorotatory) the other will rotate to the plane to the left (-, levorotatory)(equal but opposite). 
>
>###### Optical activity
>optically active substances will rotate plae polerised light. A Racemic mixture is opticcally inactive.
>
>NOTE: A Racemic mixture is a mixture containing an equal concnetration of both enantomers. 
>
>### Nomencalture.
>The + or - is prefixed to the compound name. The problem is that the + and - configuration are determined experimentally and cannot be determined dirrectly from the steriochemistry around the steriocenter.
>
>A new system was developed to overcome this problem, the process for which is as follows. 
>
> #. Priorities are assigned to each group using the C.I.P rules. (note 1 is used for highest priorety, on to 2 etc). 
> #. The molecule is orientated with the lowest priority group at the back. 
> #. If the remaining 3 substituents run from highest to lowest clockwise then the isomer is on R configuration. 
> #. If they are arranged anticlockwise the entantomer is S. 
> 
> Example: 
> Br>Cl>C>H
> 
> #. Clockwise, R
> #. anticlockwise S. 
> 
> NOTE: Flipping any two groups will result in the opposite entantomer. swapping inverts the configuration from R to S. 
> 
> ## Diasteriomers. 
>Occur if more than one steriocentre is present. Diastereomers are not mirror images.
>
>(Copy flag diagram)
>For a diassteriogentic centres there are a maximum of $2^n$
> stereoisomers. Half of these will be enantomers of the other half. 
>all of the other relationships are diateriomers. 
>
>## NMR.
>
> ### SAmple preparation. 
>COPY Image. 
>Sample in a tube which spins rapidly, and is often in solution (solid state NMR is possible but not often used). The solvent must be chosen so as not to interfere. 
>
>The most common solvent is deuterated chloroform. ($CCl_4$) is toxic, $D_2O$ and $CD_3CO_D$ are also used. (and several others copy)
>
>### Electromagnet
>jacket of liquid helium, and jacket of liquid nitrogen. 
>
>## # Analysis
>
>#### Number of signals
>
>##### Chemical shift.
>Gives information about the groups surrounding the proton in question. Each different chemical environment gives a signal.
>The first question is are the nuclei in question readily chemically distinguishable. In general it is easy to tell groups apart but more difficult within a group all attatched to the same atom and constantly rotating, (NMR cannot distinguish between them either). For all chemically equivalent  hydrogens/nuclei only one peak will be seen. For each set of protons in a unique environment a different peak will be seen.  The smae will apply to $^{13}C$ carbons. 
>
>The height of the signal depends on the time of relaxation to ground state, as a general rule quanternary carbons will relax slower giving s smaller peak. 
>
>#### Symmetry
>Symmetry implies there will be different nuclei in identical environments. 
>
>In summary the position of signals depends on the environment of the nuclei, and the number of signals depedns on how many nuclei are non equivalent. 
>
>#### Restricted rotation.
>Around a double bond consideration must be given as to what a given nuclei is cis and trans to. / 
>
>NOTE: look at Claden the second addition. 
>
>NOTE: even very similar groups which have a environment which differes to any degree will give a peak.
>
>
>### Shielding.
>Electrons are charged and moving so can set up their own field around the carbon nucelus which will slightly modify the strength of the applied field felt. As a general rule the tiny local magnetic fields that are set up oppose $H_0$. So the effective field is $H_{\text{overall}}=H_0-H_\text{electrons}$. 
>
>The extent of the field  reduction depends on the density of the electron cloud.
>
>Each nuclei experiences a different magnetic field, even though the external field is the same and therefore each nucleus resonate at its own frequency. 
>deshielded implies more of the applied field is felt. 
>
>### Chemical shift.
>The scael is universal so adjusts to the strength of the magnetic field.  ie at 60mHz 1$\delta$ unit = 60Hz, at 300mHz 1 delta unit = 300Hz. , in general $\delta $ = 1 part per million. 
>
>
>##### Referecne compound
>The compound tetramethylsilane the $\delta$ of $^{29}Si$ $^1H$ and $$^{13}C$$ are by definition given as zero.  by definition $\delta =\frac{frequency(Hz)-frequency TMS (Hz)}{instrument operating frequency MHz}$ 
>Typically H is between 0 and 10 and $^{13}C$ $0<\delta <220$
>
>
>NOTOE: the NMR is callibrated with tMS to give the zero reference value. with shielding $\delta$  will decrease this is upfield, conversely deshielding leads to increase in deshilding moving the peak downfield. 
>
>ANy carbon nucleus surrounded by protons is normally fairly shielded as the protons share electrons about equally with the carbon. If the carbon is bonded to a electronegative atom deshielding will occur, conversely if the carbon is bonded to an electropositive atom it will be more shielded, as its electron cloud will be pulled closer to it. 
>
>
>
>
>
>#### Electroinductive effect.
>Electronic effect transmitted through neighboring $\sigma$ bonds . the effect is still significant for about three bonds down the line. 
>
>NOTE: the effect is additive. 
>
>#### Unsaturation
>A ring current develops in the ring of an aromatic in this case the induced field of the $\pi$ electrons reinforces and does not reduce the applied magnetic field.
>The same is true of alkenes, and in general all unsaturated compounds. The same applies to carbons 
>
>NOTE: the protons of aldehydes are extrememly deshilded, the carbonyl carbon is generally the most deshielded carbon one will find.
>
>NOTE: alykes are a little bit of an exception as there are not as deshielded as the alkenes , READ UP ON THIS. 
>
>### Integration of signals
>NOTE: only applies to protons. 
>
>The area under a peak is proportional to the number of protons giving rise to that signal. The instrument can integrate peak areas . INtegral is plotted as steops, the height of the steps are proportional to the number of protons, integration works with protons but fails with most othe nuclei. (esp $^{13}C$ )
>
>The height signifies the number of protons, this height may nto always be exactly identical, this is not an issue and may result from some impurity in the sample. the ration between heights can then be found, the lowest whole number ration will be correct generally (as there must be a whole number and this number cannot exceed )
>---
>title: "CHEM2003 Notes"
>NOTE: the protons of aldehydes are extrememly deshilded, the carbonyl carbon is generally the most deshielded carbon one will find.
>
>NOTE: alkynes are a little bit of an exception as there are not as de-shielded as the alkenes , READ UP ON THIS. 
>
>### Integration of signals
>NOTE: only applies to protons. 
>
>The area under a peak is proportional to the number of protons giving rise to that signal. The instrument can integrate peak areas. Integral is plotted as steps, the height of the steps are proportional to the number of protons, integration works with protons but fails with most other nuclei. (esp $^{13}C$ )
>
>The height signifies the number of protons, this height may not always be exactly identical, this is not an issue and may result from some impurity in the sample. the ration between heights can then be found, the lowest whole number ration will be correct generally (as there must be a whole number and this number cannot exceed )


# Appendix

