---
title: "WCCO/Inala/COPAC: Green spaces"
output: pdf_document
---

17/07/2018

# Assigning new green spaces.
Sovereignty center can have nothing to do with Tiger brands, but other spaces are in question. Tiger brands must start to develop a new space. 

Green mapping spaces cannot be directly handed over to tiger brands. 

# If Tiger brands withdraws. 
..

## Green mapping
Meeting with the director. 

## Launch
Perhaps should not involve so many outside vendors. newline 
Date, informal\newline 

14th September as a provisional date. \newline  
Hot meal is everyday, should be on Friday. \newline 
Different meal, and perhaps catering with plates etc. \newline  

### Intertainment. 
Flash mobs, poetry etc. music, bring in connections. 
Program with different streams. 


### Event size. 
Up to 400 students, (normal day is 300), avoid making it and "even" if possible as this involves disaster management etc.  
Must have sound and plan for rain, can't be too expensive. 

NB: Requires assistance as not huge funds involves.  


## Global citizen program,
wants involvement with involvement with WCCO, \newline 
students come up with projects of campaigns, put permissions to government. Bring this in as a food seniority cause. 
Potential student campaign, \newline 

 #. Water security. 
 #. power efficiency 
 #. green spaces. 
 #. litter in inner city?
 
Proposal must come from Dean.
Proposals, water, and recycling nothing too close to home in terms of food and launch. 

## Crowd funding, must be lauched soon. 

## Note on meetings 
Inala must bring more students to meetings (*discuss with Maricia*)
and more WCCO volunteers must be involved. \newline. 
Kitchen program. 

## Harvesting. 
bring on Monday, and try involve WCCO volunteers, although this will just be part of bringing them into INALA. 

## Next meeting. 








