---
title: "R Notebook"
output: html_notebook
---

 133 
 134 (ise a third order is belw the junction of two second order streams.
 135 These orders reflect the basic rules of drainage basin geometry.  
 136 Firstly the average slope is decreasnig (normally) as first order are in moutnaous/high regions, a exception is the highveld which drains a huge high up plateu.
 137 The channel width tends to increase wiith the
 138 discharge volume increases . (as two streams are joining. )
 139 Particle size of substrata decreases, (through a filtering porcess, )
 140 
 141 §§§ DFischarge. 
 142 Dishcarge is the rate at which a volume of water flows pst a [pomt over a unit of time. 
 143 
 144 $Q=m^3s^{-1}$
 145 NOTE: $m^3s^{-1}$ are reffered to as cumecs (?) 
 146 
 147 #### Measurement. 
 148 See in back of prac handout one 
 149 
 150 The stream is divided into equal width rectangular cells vertically downwards. 
 151 The width and the depth of each cell will be measured. (the depth at the start and end of each cell is measured and averaged). A flow device is then used to             measure the vvelocity of the water going through each cell. The sum of the discharge across all cells is the transect discharge. 
 152 
 153 $Q=\displaystlye\sum _{i=1}^{n}w_id_iv_i$
 154 
 155 Dishcarge is often ,easured remotely with the use of gagine wears, which temporariily stop the flow and thenmeasure the height of the stream. Such wears are places 
     at strategic [ponyts across the catchment. 
 156 
 157 (eatern cape only on main dams, as others decomissioned in the 80s
 158 
 159 A logger logs the flow depth for every hour or half hour for months, and then the data will be retrieved by an engineer. However the data is only height , so a          racing curve, which has a relation of measures of height and discharge. (basically a standard curve. ))Discharge should be measured a bit before the wear as the         wear retards the flwo, also in a riffle/rapid there is too much turbulance, so a smooth depp laminar flow is best. N
 160 
 161 NOTE: the volume is the same thrtought but some areas are more accurate to measure. 
 162 
 163 
 164 
-- INSERT --                                                                                                                                           163,1         Bot



## Run
Such areas are reffered to as a run 

### Hydrograph 
Plots water flow against time, in a flood a rapid increase (rising limb) is seen floowed by a pea and a falling (hyperbolic) limp back to the baseline level. the peak incodes not only the flood water but also the normal baseline. Rain captured per unit time can alos be tracked and related. Ground water recession can reacharge/boost the water table raising it (ground water recession is the decrease of ground water back to its original level. , flooding recession is simple the dease in stream discharge. The size of the storm can be measured in terms of time. The center of mass of the rainstorm can be measure. The time between the heaviest rainfall and the peak detected by the wear is the basin lag. 
 The overall profile of the hydrograph can affect the flood responce. The profile of the landscape is also important. In a mountanous situation a sharper higher peak in flow will occur, whereas a plateu tends to have low sloping hydrograph. (This is becuase water is travelling faster donw the steeper gradient. )
 
 The shape of the gaging wier is also important, if there is more catchment closer than further away then the majority of the drained water is being drained closer to the wier (the majority of drainage density is close to wear), the peak will be sooner, conversely if the drainage density is concentrated further waay the peak will be lower. If there are two distinctive drainage areas one closer and on efurther there will be two peaks (a bimodal responce.) A higher drainage density leads to a higher peak. 
 
 In a trelliced catchment there is a much smaller area that can actually e drained leading to a lower hydrograph. 
 # BAnk full flodd
 Will full up the entire bank fuulled area , occurs about every year. 
 
 ### CAtsstrophic 
 About every 50 years,the depth is twice as high, as the normal one. 