---
title: "The MIND Diet"
output: pdf_document
author: "Keelan Krinksy: 1634953"
---



If four and a half billion years of evolution, twelve thousand years of agriculture and a hundred years of nutritional science (Mozaffarian _et al_, 2018) has taught us anything, it is that the importance of food simply cannot be underestimated. Indeed, the dramatic increase in human life span to double that of ancestral humans, was largely due to improved access to nutrition and medicine (Finch and Caleb,2010). Furthermore, there is now significant evidence to suggest that many major diseases such as cardiovascular disease (Mente _et al_, 2009), or cancer (Bringham and Sheila _et al_, 2004) are better combated by prevention with effective diet than direct medical treating which can be very expensive, and imply unpleasant side effects. The role of diet, in basic nutrition and disease prevention is especially evident in old age, with the increased incidence of degenerative diseases such as Alzhiemers (Arendt and Bigl, 1987). However, despite the well established importance of diet, what would constitute the ideal diet, is still not entirely clear, although many suggestions have been made. The MIND (Mediterranean-DASH Intervention for Neurodegenerative Delay) diet, is one such suggestion. It combines aspects of the classic Mediterranean diet,consisting predominately of fish, fruit and vegetables, with the newer DASH (Dietary Approaches to Stop Hypertension) diet, which includes increased dairy consumption and decreased sodium intake, to prevent nerodegenerative disease. This dietary plan has not gone without criticism,however, its overall efficacy is well supported by field trials, and it severs as a much needed guideline in the complex and confusing arena of dietary science.

To truly appreciate the advantages offered by the MIND diet requires a more detailed view of its constitutes and their metabolic effects. The mind diet is based around splitting common food sources into two general groups, brain healthy and brain unhealthy, encouraging increased consumption of the former, and decreased consumption of the latter. (Di Fiore N., 2015)  Brain healthy foods include vegetables (especially green leafy) vegetables, whole grains, berries, nuts, beans, wine (in limited quantities), fish, poultry, and olive oil, whereas brain unhealthy foods include cheese,red meats,fried foods, butter/margarine, or pastries and sweets (Marcason and Wendy,2015). All of these food groups, both healthy and unhealthy are broken down by specific anabolic pathways into their basic substituents, which can then be catabolised into new macromolecules, with the production of side/waste products along the way.(Garrett and Grisham, 4th edition). Hence, which food groups are consumed will affect the extend and amount of raw materials available for anabolism, and the exposure to toxic metabolic by products.    

The metabolism of leafy green vegetables provides a poignant example of the importance of consuming the appropriate substrates for metabolism, and the potential advantages offered by the MIND diet. Leafy greens contain significant component of proteins and carbohydrates 
(Menasah _et al_, 2018), with very low unsaturated or trans fat components. 
(Singh _et al_, 2001). The starch component of the carbohydrates present can be hydrolyzed to glucose molecules, which provide an important energy source to brain cells, which can not use any other substrate as an energy source, while many of the proteins may contain metal ion prosthetic groups, which form a vital source of micro-nutrients, for the cell. In particular the $Mg^{2+}$ ions present in the chlorophyll of such leaves is a vital co-factor for many of the enzymes involved in glycolysis, (the break down of glucose to release energy), hence without a steady supply of $Mg^{2+}$ ions the brain cells would again be starved of an energy source, among many other deleterious consequences. Finally the low 
trans and unsaturated fat concentration in leafy green helps specifically to reduce the changes of neuroegenrative disease with highly unsaturated trans fats (such as in red meat or pastries), associated with the incidence of Alzheimer's. (Morris _et al_, 2003). Similar metabolic themes can be identified for the other components of the MIND diet, to provide a thorough explanation for its contribution to decreased risk of neurodegenerative disease. 

The efficacy of the diet plan does not rest solely on theory however, as there is  also a wealth of empirical evidence linking its application to decreased incident of nerodegenerative disease. Stronger adherence to the diet has been strongly correlated to lower rates of decline in working memory, episodic memory, visiospacial ability, and perceptual speed, as general cognition scores, with strict adherence effectively delaying the deterioration process by as much as 7.5 years (Morris _et al_, 2015). Perhaps even more importantly even intermediate levels of compliance with the diet show a dramatic (35\%) reduction in the incidence of Alzheimer disease. (Moris _et al_, 2015). Furthermore the MIND diet is demonstrably more effective at Alzheimer's prevention than either of its predecessors the Mediterranean or DASH diets. (Morris _et al_, 2014). Indeed, what experimental data has been collected strongly supports the MIND diet as not only an effect, but possibly the post effective dietary choice for Alzheimer's prevention.  


However, despite the theoretical and empirical support for the diets efficacy, it is not without limitations.  Chief among these limitations is that despite the general correlation between the diet and Alzheimer's prevention discussed above, the effect of the diet on any given individual is variable, dependent upon both genetics, and behavioral patterns. (Schelke, _et al_, 2018). Inclusion of personalized nutrition, as well as cognitive activity, excessive and even social engagement regimes, in addition to the basic MIND diet, proved considerably more effective in treatment and prevention of cognitive decay. For example, insulin resistance results in glucose hypo-metabolism in the brain, and increased expression of potentially neurotoxic amyloid precursor proteins, associated with cognitive decline. (Wiette, _et al_, 2015). Adherence to the MIND diet, specifically leafy vegetables and berries which contain high concentrations of oleic acid, can show significant reductions in insulin resistance (Ryan, 2000). However, the additional consumption of cocoa favanols for individuals already following the mind diet limits insulin resistance even further. In this regard the MIND diet is not by its self the full solution for Alzheimer's prevention, as other lifestyle, and even dietary factors can have serious impacts. Nonetheless, these limitations in not way mitigate the usefulness of the diet as a general indication of cognitive healthy. Individuals who are often without the resources or inclination to adhere to more fundamental lifestyle changes can still decrease their risk of developing neurodegenerative diseases by reasonable accordance to this relatively simple diet.  

In conclusion, the MIND diet combines both the time tested Mediterranean diet, and its more recent derivative the DASH diet, to form a diet specifically tailored to prevention, and mediation of neurodegenerative disease. The diet groups common food types generally into brain healthy and brain unhealthy foods, based on the biological consequences of the metabolites which they generate, both in terms of the nutritional value of end products of metabolism as well as the potential deleterious effects of the waste/side products. The theory behind this classification relies on considerations of well established and experimentally verified metabolic pathways, and empirical trials show strong links between the diet and decreased neurodegenerative disease. While the effectiveness of the diet may vary to a degree between individuals due to genetically or behaviorally based idiosyncrasies in metabolism. However, in general it provides an easily understandable and useful guideline for neurodegenerative disease prevention, even at relatively low levels of diet compliance. High levels of diet compliance combined with bespoke modifications to the basic diet plan can lead to truly extraordinary improvements in neurodegerative disease prevention.      
\newpage

# References

Bingham Sheila, Riboli Elio,"Diet and cancer — the European Prospective Investigation into Cancer and Nutrition",_Nature Reviews Cancer_4, pp 206

Di Fiore N. 2015, "Diet may help prevent Alzeimer’s: MIND diet rich in vegetables, berries, whole grains, nuts", Rush University Medical Center website. https://www.rush.edu/news/diet-may-help-prevent-alzheimers. Accessed July 30, 2018.

Finch, Caleb E., "Evolution of the human lifespan and diseases of aging: Roles of infection, inflammation, and nutrition",107,1,1718-1724,2010, _National Academy of Sciences_,
Mente A and de Koning L and Shannon HS and Anand SS, "A systematic review of the evidence supporting a causal link between dietary factors and coronary heart disease",2009,_Archives of Internal Medicine_,169,7, pp 659-669

Garrett and Grisham,Biochemistry, 4th edition,Metabolsim:an overview, pp 546) 

JK Mensah, RI Okoli, JO Ohaju-Obodo, K Eifediy, 2008,"Phytochemical, nutritional and medical properties of some leafy vegetables consumed by Edo people of Nigeria", African,_Journal of Biotechnology_,7,14


Marcason W., 2015, "What Are the Components to the MIND Diet?"_Journal of the Academy of Nutrition and Dietetics_,115,10, pp 2212-2672


Mente A and de Koning L and Shannon HS and Anand SS,2009,"A systematic review of the evidence supporting a causal link between dietary factors and coronary heart disease",_Archives of Internal Medicine_,169,7,pp 659-669

Mozaffarian, Dariush and Rosenberg, Irwin and Uauy, Ricardo,2018 "History of modern nutrition science, implications for current research, dietary guidelines, and food policy",_BMJ_, 361,

Morris M, Evans DA, Bienias JL,2003, "Dietary fats and the risk of incident alzheimer disease",_Archives of Neurology_,60,2, pp, 194-200

Morris, M.C, C.C. Tangney, Y. Wang, 2014, "MIND diet score more predictive than DASH or MEditerranea diet scores, _Alzhiermers Dement_", 10, pp 166


Neal D. Barnard, Ashley I. Bush,Antonia Ceccarelli, James Cooper, Celeste A. de Jager, Kirk I. Erickson, Gary Fraser, Shelli Kesler, Susan M. Levin Brendan Lucey, Martha Clare Morris, Rosanna Squitti, 2014,"Dietary and lifestyle guidelines for the prevention of Alzheimer's disease",_Neurobiology of Aging_,35,pp 74-78,

Ryn,M.,2000, "Diabetes and the Mediterranean diet; a benefical efffect of oleioc acid on insulin sensitivity, adipocyte glucose tansport adn endothelium-dependant vasoreactivity", _QJM_, 93, pp 85-91

Schelke, Matthew W. Hackett, Katherine Chen, Jaclyn L. Shih, Chiashin Shum, Jessica Montgomery, Mary E. Chiang, Gloria C. Berkowitz, Cara Seifan, Alon Krikorian, Robert Isaacson, Richard Scott}, "Nutritional interventions for Alzheimer's prevention: a clinical precision medicine approach", _New York Academy of Sciences_,1367,1, pp 50-56
 
Singh, G. Kawatra, Asha Sehgal,2001,"Nutritional composition of selected green leafy vegetables, herbs and carrots", _Plant Foods for Human Nutrition_,56,4, pp 359-364.

Thomas Arendt, Volker Bigl, 1987,"Alzheimer's disease as a presumptive threshold phenomenon", _Neurobiology of Aging_,8,6,pp 552-554

Willette A.A., B.B Bendlin, E.J. Starks, 2015,"Association of insulin resistance with cerebral glucose uptake in late middle-aged adults at risk for Alzheimer disease", _JAMA Neurol_ ,72, pp 1013





 
 

