---
title: "The MIND Diet"
output: pdf_document
---

If four and a half billion years of evolution, twelve thousand years of agriculture and a hundered years of nutritional science (Mozaffarian et al, 2018) has taught us anything, it is that the importance of food simply cannot be underestimated. Indeed, the dramatic increase in human life span to doulbe that of ancestral humans, was largely due to improved access to nutrition and medicine (Finch and Caleb,2010). Furthermore, there is now significant evidence to suggest that many major diseases such as cardiovascular disease (Mente et al, 2009), or cancer (Bringham nad Sheila et al, 2004) are better combatted by prevention with effective diet than dirrect medical treating which can be very expensive, and imply unpleasant side effects. The role of diet, in basic nutrition and disease prevention is especially evident in old age, with the increased incidence of degenerative diseases such as Altzhiemers (Arendt and Bigl, 1987). However, dispite the well established importance of diet, what would constitute the ideal diet, is still not entirely clear, although many sugesstions have been made. The MIND (Mediterranean-DASH Intervention for Neurodegenerative Delay) diet, is one such suggestion. It combines aspects of the classic medeteranian diet,consisting predominately of fish, fruit and vegitables, with the newer DASH (Dietary Approaches to Stop Hypertension) diet, which includes increased dairy consuption and decreased sodium intake, to prevent nerodegenerative disease. This dietary plan has not gone without critisicm,however, its overall efficacy is well supported by field trials, and it severes as a much needed guidline in the complex and confusing arena of dietary science.

To truely appreciate the advantages offered by the MIND diet requires a more detailed view of its consituets and their metabolic effects. 

The metabolic effects is that. 

This improves the 


# References

 #. @article{ARENDT1987552,
title = "Alzheimer's disease as a presumptive threshold phenomenon",
journal = "Neurobiology of Aging",
volume = "8",
number = "6",
pages = "552 - 554",
year = "1987",
issn = "0197-4580",
doi = "https://doi.org/10.1016/0197-4580(87)90131-X",
url = "http://www.sciencedirect.com/science/article/pii/019745808790131X",
author = "Thomas Arendt and Volker Bigl"
} 
 
 #. TY  - JOUR
AU  - Bingham, Sheila
AU  - Riboli, Elio
TI  - Diet and cancer — the European Prospective Investigation into Cancer and Nutrition
JO  - Nature Reviews Cancer
PY  - 2004/03/01/online
VL  - 4
SP  - 206
EP  -
PB  - Nature Publishing Group
SN  -
UR  - http://dx.doi.org/10.1038/nrc1298
L3  - 10.1038/nrc1298
M3  - Review Article
L3  - 
ER  -

 #. @article{doi:10.1001/archinternmed.2009.38,
author = {Mente A and de Koning L and Shannon HS and Anand SS},
title = {A systematic review of the evidence supporting a causal link between dietary factors and coronary heart disease},
journal = {Archives of Internal Medicine},
volume = {169},
number = {7},
pages = {659-669},
year = {2009},
doi = {10.1001/archinternmed.2009.38},
URL = { + http://dx.doi.org/10.1001/archinternmed.2009.38},
eprint = {/data/journals/intemed/22596/ira80010_659_669.pdf}
} 

 #. @article {Mozaffariank2392,
	author = {Mozaffarian, Dariush and Rosenberg, Irwin and Uauy, Ricardo},
	title = {History of modern nutrition science{\textemdash}implications for current research, dietary guidelines, and food policy},
	volume = {361},
	year = {2018},
	doi = {10.1136/bmj.k2392},
	publisher = {BMJ Publishing Group Ltd},
	issn = {0959-8138},
	URL = {https://www.bmj.com/content/361/bmj.k2392},
	eprint = {https://www.bmj.com/content/361/bmj.k2392.full.pdf},
	journal = {BMJ} 



 #. @article {Finch1718,
	author = {Finch, Caleb E.},
	title = {Evolution of the human lifespan and diseases of aging: Roles of infection, inflammation, and nutrition},
	volume = {107},
	number = {suppl 1},
	pages = {1718--1724},
	year = {2010},
	doi = {10.1073/pnas.0909606106},
	publisher = {National Academy of Sciences},
	abstract = {Humans have evolved much longer lifespans than the great apes, which rarely exceed 50 years. Since 1800, lifespans have doubled again, largely due to improvements in environment, food, and medicine that minimized mortality at earlier ages. Infections cause most mortality in wild chimpanzees and in traditional forager-farmers with limited access to modern medicine. Although we know little of the diseases of aging under premodern conditions, in captivity, chimpanzees present a lower incidence of cancer, ischemic heart disease, and neurodegeneration than current human populations. These major differences in pathology of aging are discussed in terms of genes that mediate infection, inflammation, and nutrition. Apolipoprotein E alleles are proposed as a prototype of pleiotropic genes, which influence immune responses, arterial and Alzheimer{\textquoteright}s disease, and brain development.},
	issn = {0027-8424},
	URL = {http://www.pnas.org/content/107/suppl_1/1718},
	eprint = {http://www.pnas.org/content/107/suppl_1/1718.full.pdf},
	journal = {Proceedings of the National Academy of Sciences}
}


#. @article{doi:10.1001/archinternmed.2009.38,
author = {Mente A and de Koning L and Shannon HS and Anand SS},
title = {A systematic review of the evidence supporting a causal link between dietary factors and coronary heart disease},
journal = {Archives of Internal Medicine},
volume = {169},
number = {7},
pages = {659-669},
year = {2009},
doi = {10.1001/archinternmed.2009.38},
URL = { + http://dx.doi.org/10.1001/archinternmed.2009.38},
eprint = {/data/journals/intemed/22596/ira80010_659_669.pdf}
}